<a href="https://colab.research.google.com/github/DawidSzoka1/machine-learning/blob/main/data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Standaryzacja danych
# (x - x.mean()) / x.std()

###Zmiana danych z tektu na liczy w pandas
#pd.get_dummies()

In [1]:
!pip install scikit-learn

In [2]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.2.2'

In [3]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [60]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [61]:
for col in df.columns:
  if col != 'weight' and col !=  'price':
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [62]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [63]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

###LabelEncoder stosujemy ja raczej do zmiennych docelowych (target) do zmiennych wejsciowych uzyjemy innej funkcji/metody/obiektu

In [64]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [65]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [66]:
le.classes_

array(['no', 'yes'], dtype=object)

In [67]:
df['bought'] = le.fit_transform(df['bought'])

#Zmienia dane obiektowe tekstowe na numaryczna

do odwrocenia tych danych uzyjemy le.inverse_transform(df['bought'])

In [68]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [69]:
le.fit_transform(df['color'])

array([2, 1, 0, 1, 2])

### OneHotEncoder


In [70]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse_output=False)

sparse_output=False sprawi ze dane beda do wyswietlenia inaczej jest to macierz rzadka po prostu beda tylko pozycje na ktorych jest jedynka

In [71]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [72]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [73]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [74]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

##Zawsze po takich operacjach po przekszatlceniu uzyskamy o jedna kolumne mniej niz mielismy wczesnie np jak mamy dwa wybory czyli albo kupione albo nie to chcemy miec jedna kolumne jak mamy trzy kolory to chcemy miec kolumne z dwoma kolorami i wartosciami 1 lub 0 a tam gdzie sa 2 0 mamy trzeci kolor

In [75]:
pd.get_dummies(df, drop_first=True)

price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  199.0   500.0       1   False     True        False       True        False
1   89.0   450.0       0   False    False         True      False         True
2   99.0   300.0       1    True    False        False      False         True
3  129.0   380.0       0   False    False         True      False        False
4   79.0   410.0       1    True    False        False       True        False

In [76]:
pd.get_dummies(df, drop_first=True, prefix='new')

price  weight  bought  new_M  new_XL  new_green  new_red  new_male
0  199.0   500.0       1  False    True      False     True     False
1   89.0   450.0       0  False   False       True    False      True
2   99.0   300.0       1   True   False      False    False      True
3  129.0   380.0       0  False   False       True    False     False
4   79.0   410.0       1   True   False      False     True     False

In [77]:
pd.get_dummies(df, drop_first=True, columns=['size'])

color  gender  price  weight  bought  size_M  size_XL
0    red  female  199.0   500.0       1   False     True
1  green    male   89.0   450.0       0   False    False
2   blue    male   99.0   300.0       1    True    False
3  green  female  129.0   380.0       0   False    False
4    red  female   79.0   410.0       1    True    False

In [78]:
def standardize(x):
  if isinstance(x, pd.Series):
    return (x - x.mean()) / x.std()
  return 'zly typ danych'

In [79]:
standardize(df_raw['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [80]:
from sklearn.preprocessing import scale

scale(df_raw['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

##Wartosci sie roznia bo estymatora obciazonego warianci

In [81]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df_raw[['price']])
scaler.transform(df_raw[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [85]:
scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

size  color  gender     price    weight  bought
0   XL    red  female  1.845062  1.366002       1
1    L  green    male -0.691898  0.623610       0
2    M   blue    male -0.461266 -1.603567       1
3    L  green  female  0.230633 -0.415740       0
4    M    red  female -0.922531  0.029696       1

In [93]:
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [94]:
df[['price', 'weight']] = StandardScaler().fit_transform(df[['price', 'weight']])
df['bought'] = LabelEncoder().fit_transform(df['bought'])
df = pd.get_dummies(df, drop_first=True)
df

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1   False     True        False       True   
1 -0.691898  0.623610       0   False    False         True      False   
2 -0.461266 -1.603567       1    True    False        False      False   
3  0.230633 -0.415740       0   False    False         True      False   
4 -0.922531  0.029696       1    True    False        False       True   

   gender_male  
0        False  
1         True  
2         True  
3        False  
4        False

price    weight  size_M  size_XL  color_green  color_red  gender_male  \
0  1.845062  1.366002   False     True        False       True        False   
1 -0.691898  0.623610   False    False         True      False         True   
2 -0.461266 -1.603567    True    False        False      False         True   
3  0.230633 -0.415740   False    False         True      False        False   
4 -0.922531  0.029696    True    False        False       True        False   

   bought_yes  
0        True  
1       False  
2        True  
3       False  
4        True