<a href="https://colab.research.google.com/github/DawidSzoka1/machine-learning/blob/main/data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Standaryzacja danych
# (x - x.mean()) / x.std()

###Zmiana danych z tektu na liczy w pandas
#pd.get_dummies()

In [1]:
!pip install scikit-learn

In [2]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.2.2'

In [3]:
data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [13]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


In [14]:
for col in df.columns:
  if col != 'weight' and col !=  'price':
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [16]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [17]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

###LabelEncoder stosujemy ja raczej do zmiennych docelowych (target) do zmiennych wejsciowych uzyjemy innej funkcji/metody/obiektu

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [19]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [20]:
le.classes_

array(['no', 'yes'], dtype=object)

In [21]:
df['bought'] = le.fit_transform(df['bought'])

#Zmienia dane obiektowe tekstowe na numaryczna

do odwrocenia tych danych uzyjemy le.inverse_transform(df['bought'])

In [22]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [25]:
df['weight'] = (df['weight'] - df['weight'].mean())/ df['weight'].std()
df['price'] = (df['price'] - df['price'].mean())/ df['price'].std()

In [26]:
df

size  color  gender     price    weight  bought
0   XL    red  female  1.650274  1.221789       1
1    L  green    male -0.618853  0.557773       0
2    M   blue    male -0.412568 -1.434274       1
3    L  green  female  0.206284 -0.371849       0
4    M    red  female -0.825137  0.026561       1

In [28]:
le.fit_transform(df['color'])

array([2, 1, 0, 1, 2])