<a href="https://colab.research.google.com/github/DawidSzoka1/machine-learning/blob/main/Gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

In [3]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
print(X1)
print(Y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[3000]
 [3250]
 [3500]
 [3750]
 [4000]
 [4250]]


In [4]:
bias = np.ones((m,1))
print(bias)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [5]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


In [23]:
learning_rate = 0.01

W = np.random.randn(2,1)
print(X)
print(W)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[-1.72491783]
 [-0.56228753]]


In [24]:
intercept = []
coef = []

for i in range(3000):
  gradient = (2/m) * X.T.dot(X.dot(W) - Y)
  W = W - learning_rate * gradient
  intercept.append(W[0][0])
  coef.append(W[1][0])

print(W)

[[2749.9559742 ]
 [ 250.01028352]]


In [25]:
df = pd.DataFrame(data={'intercept': intercept, 'coef': coef})

In [26]:
df.head()

intercept        coef
0   70.848941  268.062351
1  123.167597  450.124012
2  161.695565  573.297996
3  190.830793  656.412248
4  213.565320  712.275711

In [27]:
px.line(df, y='intercept', width=800)

In [28]:
px.line(df, y='coef', width=800)